name: Test coverage
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  tics-report:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dotrun
        run: |
          sudo pip3 install dotrun

      - name: Install LXD-UI dependencies
        run: |
          set -x
          sudo chmod 0777 ../lxd-ui
          dotrun install

      - name: Produce TICS report
        shell: bash
        run: |
          set -x
          export TICSAUTHTOKEN=${{ secrets.TICSAUTHTOKEN }} # zizmor: ignore[secrets-outside-env]
          # need to source .profile, or TICSQServer command won't be found
          source ~/.profile
          # Update path so eslint is used through yarn dependencies
          export PATH="$PWD/node_modules/.bin:$PATH"
          which eslint
          find . | grep eslint
          TICSQServer -project lxd-ui -tmpdir /tmp/tics -branchdir .
